modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Beautified%20Chat%20Client"
logoFile="icon.png"

[[mods]]
modId="beautifiedchatclient"
version="2.4"
displayName="Beautified Chat Client"
displayURL="https://serilum.com/mod/beautified-chat-client"
authors="Rick South"
description='''A highly configurable mod to change the style and colour of incoming chat messages on the client.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.beautifiedchatclient]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beautifiedchatclient]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"